In [80]:
import numpy as np
import math
import pandas as pd
#import sys
#print(sys.executable) 

"""the above lines are for me to show where to install packages, pandas was giving me grief prior, 
for future reese, run the code, paste output into terminal followed by "-m pip install [package]
"""




'the above lines are for me to show where to install packages, pandas was giving me grief prior, \nfor future reese, run the code, paste output into terminal followed by "-m pip install [package]\n'

Creating Arrays:

    Create a one-dimensional array of integers from 0 to 9.
    Create a two-dimensional array of zeros with shape (5, 5).
    Create a three-dimensional array of ones with shape (2, 3, 4).


In [2]:
#first = np.array([0,1,2,3,4,5,6,7,8,9])
# alternative below:
first = np.arange(10)
print(first)
second = np.zeros((5,5))
print(second)
third = np.ones((2,3,4))
print(third)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Manipulating Arrays:

    Reshape the above two-dimensional array to a one-dimensional array.
    Stack two arrays horizontally and vertically.
    Split a given array into multiple sub-arrays.
    Flatten a multi-dimensional array.
    Expand the dimensions of a one-dimensional array.


In [3]:
secondres = np.reshape(second,(25))
print(1)
print(secondres)
combo1 = np.ones((2,3))
combo0 = np.zeros((2,3))
vertstack = np.vstack((combo0,combo1))
horstack = np.hstack((combo0,combo1))
print(2)
print(vertstack)
print(horstack)

zplit = np.split(combo1,2)
print(3)
print(zplit)
flatray = combo1.flatten()
print(4)
print(flatray)
print(flatray.shape)
expray =  np.expand_dims(flatray,0)
print(5)
print(expray.shape)
print(expray)

1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
2
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
3
[array([[1., 1., 1.]]), array([[1., 1., 1.]])]
4
[1. 1. 1. 1. 1. 1.]
(6,)
5
(1, 6)
[[1. 1. 1. 1. 1. 1.]]


Array Indexing:

    Extract the third and fifth elements from a one-dimensional array.
    Extract a 2x2 sub-matrix from a given two-dimensional array.
    Use boolean indexing to extract even numbers from an array.


In [4]:
first = np.arange(10)
element3 = first[3]
element5 = first[5]
print(element3)
print(element5)
#sample array:
second = np.arange(10).reshape(2,5)
def yoinksubarray(arr,startr,startc):
    subarray = arr[startr:startr+2,startc:startc+2]
    return subarray
#sample of function:
yoinksubarray(second,0,2)


# Example array
third = np.array([[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10]])

# Boolean indexing to extract even numbers
even_numbers = third[third % 2 == 0]

print("Original Array:")
print(third)
print("\nEven Numbers:")
print(even_numbers)

3
5
Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Even Numbers:
[ 2  4  6  8 10]


Arithmetic Operations:

    Perform element-wise addition, subtraction, multiplication, and division on two given arrays.
    Multiply a 2x3 matrix with a 1x3 matrix using broadcasting.


In [5]:
def adder(x,y):
    z=x + y
    print(z)

x1 = np.arange(10)
y1 = x1
adder(x1,y1)
def subber(x,y):
    z=x - y
    print(z)

subber(x1,y1)

def multer(x,y):
    z = np.multiply(x,y)
    print(z)

x2 = np.arange(6).reshape(2,3)
y2 = np.arange(3)
multer(x2,y2)

def divver(x,y):
    z= np.divide(x,y)
    print(z)

y3 = np.array([1,2,3])

divver(x2,y3)

#last bit about broadcasting
z1 = np.broadcast(x2,y2)
out = np.empty(z1.shape)
out.flat = [u*v for (u,v) in z1]
print(out)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[[ 0  1  4]
 [ 0  4 10]]
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]]
[[ 0.  1.  4.]
 [ 0.  4. 10.]]


Aggregation Functions:

    Calculate the sum, mean, standard deviation, and variance of a one-dimensional array.
    Find the minimum and maximum values in a one-dimensional array.
    Repeat (a) and (b) along a single axis of a two-dimensional array.


In [6]:
#a1
testarray = np.arange(10)
testsu = np.sum(testarray)
testme = np.mean(testarray)
testst = np.std(testarray)
testva = np.var(testarray)

print("sum: "+str(testsu))
print("mean: "+str(testme))
print("stdev: "+str(testst))
print("variance: "+str(testva))

#b1

print("min: "+str(np.min(testarray)))
print("max: "+str(np.max(testarray)))


#a2
practice_matrix = np.arange(25).reshape(5,5)
print(practice_matrix)

def MathForOneRow(x):
    testsu1 = np.sum(practice_matrix[x])
    testme1 = np.mean(practice_matrix[x])
    testst1 = np.std(practice_matrix[x])
    testva1 = np.var(practice_matrix[x])
    #a
    print("sum: "+str(testsu1))
    print("mean: "+str(testme1))
    print("stdev: "+str(testst1))
    print("variance: "+str(testva1))

    #b
    print("min: "+str(np.min(practice_matrix[x])))
    print("max: "+str(np.max(practice_matrix[x])))



print("checking with row 1")
MathForOneRow(1)


sum: 45
mean: 4.5
stdev: 2.8722813232690143
variance: 8.25
min: 0
max: 9
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
checking with row 1
sum: 35
mean: 7.0
stdev: 1.4142135623730951
variance: 2.0
min: 5
max: 9


Linear Algebra:

    Transpose a matrix
    Multiply two matrices.
    Compute the dot product of two vectors.
    Calculate the determinant of a matrix.
    Compute the eigenvalues and eigenvectors of a matrix.
    Solve a system of linear equations using NumPy.


In [7]:
practice_matrix = np.arange(9).reshape(3,3)
testtrans = practice_matrix.transpose()
print(practice_matrix)
print(testtrans)

multpractice = np.matmul(practice_matrix,testtrans)
print(multpractice)

vec1 = np.arange(4)
vec2 = np.array([5,7,9,11])
dotprod = np.dot(vec1,vec2)
print(dotprod)


detpractice = np.array([[3,0],[0,4]])
testdet = np.linalg.det(detpractice)
print(testdet)

testeig = np.linalg.eig(detpractice)
print(testeig)

testind = np.array([[5,3],[1,2]])
testdep = np.array([[1],[2]])
print("the solution set to :")
print("5x+3y=1;x+2y=2")
print(np.linalg.solve(testind,testdep))




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
58
12.0
EigResult(eigenvalues=array([3., 4.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))
the solution set to :
5x+3y=1;x+2y=2
[[-0.57142857]
 [ 1.28571429]]


Simulation:

    Simulate 100 steps of a random walk with standard normal innovations.
    Generate 1,000 simulations of the random walk from part (a). Compute the mean, median, and standard deviation of the terminal value across the 1,000 simulations.


In [8]:
simsample = []
BigCount = 0
while BigCount < 1000:
    smallcount = 0
    x=0
    while smallcount < 100:
        x = x + np.random.normal()
        smallcount += 1
    simsample.append(x)
    BigCount += 1


print("mean:"+str(np.mean(simsample)))
print("median:"+str(np.median(simsample)))
print("SD:"+str(np.std(simsample)))


### for giggles, chatGPT's code

# Set the number of steps and simulations
num_steps = 100
num_simulations = 1000

# Create an array to store terminal values
terminal_values = np.zeros(num_simulations)

# Perform simulations
for i in range(num_simulations):
    # Generate standard normal innovations for each step
    innovations = np.random.standard_normal(num_steps)
    
    # Calculate the cumulative sum to simulate the random walk
    random_walk = np.cumsum(innovations)
    
    # Store the terminal value after 100 steps
    terminal_values[i] = random_walk[-1]

# Calculate mean, median, and standard deviation of terminal values
mean_terminal = np.mean(terminal_values)
median_terminal = np.median(terminal_values)
std_dev_terminal = np.std(terminal_values)

# Print the results
print(f"GPT Says : Mean of terminal values: {mean_terminal:.4f}")
print(f"GPT Says : Median of terminal values: {median_terminal:.4f}")
print(f"GPT Says : Standard Deviation of terminal values: {std_dev_terminal:.4f}")


mean:0.42967327094886887
median:0.07899373894831047
SD:9.8590979501602
GPT Says : Mean of terminal values: -0.0394
GPT Says : Median of terminal values: 0.1298
GPT Says : Standard Deviation of terminal values: 9.8990


    Create a series from a list of integers.
    Extract values at specific indices from the Series.
    Change the index of the series to alphabetical letters.
    Create a dataFrame from a dictionary of lists.
    Extract specific columns from the dataFrame.
    Add a new column to the dataFrame.
    Create a dataframe filled with random numbers.


In [99]:
#1
listoints = [0,1,2,3,6,7,9,20,5318008]
aseriesofints = pd.Series(listoints)
print(aseriesofints)
#2
extractedvals = aseriesofints[[0,2,5]]
print()
print(extractedvals)
#3
extractedvals.index = ["a","b","c"]
print()
print(extractedvals)
#4
list1 = ["a","b","c","d"]

list2 = [1,2,3,4]
list3 = ["reese","kerry","august","mert"]

mydict = {"list1":list1,"list2":list2,"list3":list3}

mydf = pd.DataFrame(mydict)

print()
print(mydf)
#5
print()
print(mydf[["list2","list3"]])
#6
print()
mydf["newstuff"] = -mydf["list2"]
print(mydf)
#7

# Generating a 5x3 array of random integers between 0 and 100
random_data = np.random.randint(0, 100, size=(5, 3))
# Creating a DataFrame from the random data
random_df = pd.DataFrame(random_data, columns=['Column1', 'Column2', 'Column3'])
random_df

0          0
1          1
2          2
3          3
4          6
5          7
6          9
7         20
8    5318008
dtype: int64

0    0
2    2
5    7
dtype: int64

a    0
b    2
c    7
dtype: int64

  list1  list2   list3
0     a      1   reese
1     b      2   kerry
2     c      3  august
3     d      4    mert

   list2   list3
0      1   reese
1      2   kerry
2      3  august
3      4    mert

  list1  list2   list3  newstuff
0     a      1   reese        -1
1     b      2   kerry        -2
2     c      3  august        -3
3     d      4    mert        -4


Column1  Column2  Column3
0       14       37       68
1        1       68       49
2       99       53       62
3       75       75       83
4       71       86       35


    Calculate the summary statistics for a DataFrame column.
    Sort the dataFrame based on a specific column.
    Filter rows based on certain criteria.
    Replace specific values in a DataFrame.
    Rename columns.
    Map values in a column to other values using a dictionary.


In [115]:
tempmydf = mydf.copy()
#mean of column 2

print("the mean of col2 is " + str(np.mean(mydf["list2"])))
sorteddf = mydf.sort_values("newstuff")
print("reversing by the negative row")
print(sorteddf)

conditionalthing = ~(mydf["list3"]== "reese")
filterdf = mydf[conditionalthing]
print("filtered myself out")
print(filterdf)

#replace a specific value


tempmydf.loc[0,"list3"]="Reese"
print("sorry for got to capitalize my name")
print(tempmydf)

replace_columns = {"list1":"letters","list2":"numbers","list3":"names","newstuff":"negatives"}
tempmydf = tempmydf.rename(replace_columns,axis=1)

print(tempmydf)
replace_vals = {1:"w",2:"h",3:"a",4:"t"}
tempmydf["numbers"] = tempmydf["numbers"].replace(replace_vals)
print(tempmydf)

the mean of col2 is 2.5
reversing by the negative row
  list1  list2   list3  newstuff
3     d      4    mert        -4
2     c      3  august        -3
1     b      2   kerry        -2
0     a      1   reese        -1
filtered myself out
  list1  list2   list3  newstuff
1     b      2   kerry        -2
2     c      3  august        -3
3     d      4    mert        -4
sorry for got to capitalize my name
  list1  list2   list3  newstuff
0     a      1   Reese        -1
1     b      2   kerry        -2
2     c      3  august        -3
3     d      4    mert        -4
  letters  numbers   names  negatives
0       a        1   Reese         -1
1       b        2   kerry         -2
2       c        3  august         -3
3       d        4    mert         -4
  letters numbers   names  negatives
0       a       w   Reese         -1
1       b       h   kerry         -2
2       c       a  august         -3
3       d       t    mert         -4



    Find all missing values in a DataFrame. 
    Fill missing values with zeros.
    Fill missing values in a column with the column’s mean value.
    Drop rows with missing data.
    Find duplicate rows.
    Drop all but the last row in each set of duplicate rows.


In [134]:
tempmydf = mydf.copy()

tempmydf.loc[0,"list3"]=np.nan
tempmydf.loc[2,"list2"]=np.nan
print(tempmydf)

tempmydf=tempmydf.fillna(0)
print(tempmydf)
print("dropping column 1,3 so that means can be calc'd, and replace one NaN")
tempmydf = mydf.copy()
tempmydf.loc[2,"list2"]=np.nan
dropsforalphas = ["list1","list3"]
tempmydf = tempmydf.drop(dropsforalphas,axis=1)
tempmydf = tempmydf.fillna(tempmydf.mean())
print(tempmydf)

tempmydf = mydf.copy()

tempmydf.loc[0,"list3"]=np.nan
tempmydf.loc[2,"list2"]=np.nan

tempmydf = tempmydf.dropna(axis=0)
print(tempmydf)

tempmydf = mydf.copy()

tempmydf.loc[len(tempmydf.index)]=['d',4.0,"mert",-4]
print(tempmydf)
tempmydf = tempmydf.drop_duplicates(keep='last')
print(tempmydf)

  list1  list2   list3  newstuff
0     a    1.0     NaN        -1
1     b    2.0   kerry        -2
2     c    NaN  august        -3
3     d    4.0    mert        -4
  list1  list2   list3  newstuff
0     a    1.0       0        -1
1     b    2.0   kerry        -2
2     c    0.0  august        -3
3     d    4.0    mert        -4
dropping column 1,3 so that means can be calc'd, and replace one NaN
      list2  newstuff
0  1.000000        -1
1  2.000000        -2
2  2.333333        -3
3  4.000000        -4
  list1  list2  list3  newstuff
1     b    2.0  kerry        -2
3     d    4.0   mert        -4
  list1  list2   list3  newstuff
0     a    1.0   reese        -1
1     b    2.0   kerry        -2
2     c    3.0  august        -3
3     d    4.0    mert        -4
4     d    4.0    mert        -4
  list1  list2   list3  newstuff
0     a    1.0   reese        -1
1     b    2.0   kerry        -2
2     c    3.0  august        -3
4     d    4.0    mert        -4



    Using the ‘tips’ dataset, filter the rows where the total bill is greater than $10.
    Create a new column in the ‘tips’ dataset called ‘bill_per_person’ which is the total bill divided by the size of the party.
    Group by the ‘day’ column and compute the average total bill for each day.


In [144]:
import seaborn as sns

tips = sns.load_dataset('tips')
condition_1 = tips['total_bill'] > 10.0
filtered_df_1 = tips[condition_1]
print(filtered_df_1)
tips["perperson"]= tips['total_bill'] / tips['size']
print(tips.head())
daytodayave = tips.groupby("day", observed='false')["total_bill"].mean()
print(daytodayave)


     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[227 rows x 7 columns]
   total_bill   tip     sex smoker  day    time  size  perperson
0       16.99  1.01  Female     No  Sun  Dinner     2   8.495000
1       10.34  1.66    Male     No  Sun  Dinner     3   3.446667
2       21.01  3.50    Male     No  Sun  Dinner     3   7.003333
3       23.68  3.31    Male     